import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { getPostgresPool } from "../src/lib/db/postgres.ts";
import { resolveWaypostUserId } from "../src/lib/users/identity.ts";
import { getTripCreditBalance, TripCreditError } from "../src/lib/credits/repository.ts";
import { commitOwnedTripFinalization, createTripWithDraft, refreshOwnedFinalRouteCache } from "../src/lib/trips/repository.ts";
import { finalizeOwnedTrip } from "../src/lib/trips/finalization.ts";
import type { FinalRoutePreview } from "../src/types/final-route.ts";
import type { TripDraft } from "../src/types/trip.ts";

const pool=getPostgresPool(); const users:string[]=[];
const draft:TripDraft={origin:{label:"A",coordinates:{lat:35,lon:-80}},stop:null,destination:{label:"B",coordinates:{lat:36,lon:-79}},route:{type:"Feature",properties:{},geometry:{type:"LineString",coordinates:[[-80,35],[-79,36]]}},summary:{distanceKm:1,durationSeconds:1,hasToll:false,hasHighway:false,hasFerry:false},baselineSummary:{distanceKm:1,durationSeconds:1,hasToll:false,hasHighway:false,hasFerry:false},stops:[],alternatives:[],lastEdit:null,preferences:{preferredCategories:[],excludedCategories:[],detourTolerance:"balanced",stopStyle:"balanced",drivingPace:"balanced",selectedTripDays:1,tripDaysOverridden:true},multiDay:{isMultiDay:false,drivingPace:"balanced",recommendedDays:1,selectedDays:1,nights:0,baselineDrivingHours:1,dayOptions:[1]},overnightAlternatives:[],dayPlans:[],composition:{targetPoiCount:0,selectedPoiCount:0,detourBudgetSeconds:0,actualDetourSeconds:0,actualDetourWasClamped:false,valhallaCallCount:1,corridorCandidateCount:0,candidateCountConsidered:0,candidatesAfterDeduplication:0,opportunityShortlistSize:0,candidatePoolTruncated:false,suggestedVisitDuration:{minimumMinutes:0,maximumMinutes:0,hasUnknown:false}}};
const here:FinalRoutePreview={provider:"here",route:{type:"LineString",coordinates:[[-80,35],[-79,36]]},summary:{distanceKm:1,durationSeconds:1,baseDurationSeconds:1},diagnostics:{waypointCount:2,sectionCount:1,requestDurationMilliseconds:1}};
async function user(){const id=await resolveWaypostUserId(`local:credit-test:${randomUUID()}`);users.push(id);return id;}
async function trip(userId:string){const value=await createTripWithDraft(userId,draft);if(!value?.currentVersion)throw new Error("fixture");return value;}
try{
  await pool.query("DELETE FROM public.trips WHERE user_id IN (SELECT id FROM public.users WHERE auth_subject LIKE 'local:credit-test:%')");
  await pool.query("DELETE FROM public.users WHERE auth_subject LIKE 'local:credit-test:%'");
  const backfill=await pool.query("SELECT count(*)::int AS missing FROM public.users u LEFT JOIN public.trip_credit_accounts a ON a.user_id=u.id LEFT JOIN public.trip_credit_ledger l ON l.user_id=u.id AND l.idempotency_key='welcome:'||u.id::text WHERE a.user_id IS NULL OR l.id IS NULL");assert.equal(backfill.rows[0].missing,0);
  const a=await user();assert.equal(await resolveWaypostUserId((await pool.query("SELECT auth_subject FROM public.users WHERE id=$1",[a])).rows[0].auth_subject),a);assert.equal(await getTripCreditBalance(a),1);assert.equal((await pool.query("SELECT count(*)::int count FROM public.trip_credit_ledger WHERE user_id=$1 AND entry_type='welcome_grant'",[a])).rows[0].count,1);
  const first=await trip(a);const finalized=await commitOwnedTripFinalization(a,first.id,first.currentVersion!.id,first.currentVersion!.updatedAt,here);assert.equal(await getTripCreditBalance(a),0);let retryHereCalls=0;const retry=await finalizeOwnedTrip(a,first.id,{calculateRoute:async()=>{retryHereCalls+=1;return here;}});assert.equal(retry.cache.fetchedAt,finalized.cache.fetchedAt);assert.equal(retryHereCalls,0);assert.equal((await pool.query("SELECT count(*)::int count FROM public.trip_credit_ledger WHERE trip_version_id=$1",[first.currentVersion!.id])).rows[0].count,1);
  await pool.query("UPDATE public.provider_route_cache SET fetched_at=now()-interval '31 days',expires_at=now()-interval '1 minute' WHERE trip_version_id=$1",[first.currentVersion!.id]);const ledgerBefore=(await pool.query("SELECT count(*)::int count FROM public.trip_credit_ledger WHERE user_id=$1",[a])).rows[0].count;await refreshOwnedFinalRouteCache(a,first.id,first.currentVersion!.id,here);assert.equal(await getTripCreditBalance(a),0);assert.equal((await pool.query("SELECT count(*)::int count FROM public.trip_credit_ledger WHERE user_id=$1",[a])).rows[0].count,ledgerBefore);
  const second=await trip(a);let zeroBalanceHereCalls=0;await assert.rejects(()=>finalizeOwnedTrip(a,second.id,{calculateRoute:async()=>{zeroBalanceHereCalls+=1;return here;}}),(e:unknown)=>e instanceof TripCreditError);assert.equal(zeroBalanceHereCalls,0);const secondState=(await pool.query("SELECT t.status,v.state,(SELECT count(*)::int FROM public.provider_route_cache WHERE trip_version_id=v.id) cache_count FROM public.trips t JOIN public.trip_versions v ON v.id=t.current_version_id WHERE t.id=$1",[second.id])).rows[0];assert.deepEqual(secondState,{status:"draft",state:"draft",cache_count:0});
  const failureUser=await user();const failedTrip=await trip(failureUser);await assert.rejects(()=>finalizeOwnedTrip(failureUser,failedTrip.id,{calculateRoute:async()=>{throw new Error("provider failed");}}));assert.equal(await getTripCreditBalance(failureUser),1);assert.equal((await pool.query("SELECT count(*)::int count FROM public.provider_route_cache WHERE trip_version_id=$1",[failedTrip.currentVersion!.id])).rows[0].count,0);
  const b=await user();const [raceA,raceB]=await Promise.all([trip(b),trip(b)]);const race=await Promise.allSettled([commitOwnedTripFinalization(b,raceA.id,raceA.currentVersion!.id,raceA.currentVersion!.updatedAt,here),commitOwnedTripFinalization(b,raceB.id,raceB.currentVersion!.id,raceB.currentVersion!.updatedAt,here)]);assert.equal(race.filter(x=>x.status==="fulfilled").length,1);assert.equal(await getTripCreditBalance(b),0);
  const reconciliation=await pool.query("SELECT a.balance,COALESCE(SUM(l.amount),0)::int ledger_balance FROM public.trip_credit_accounts a LEFT JOIN public.trip_credit_ledger l ON l.user_id=a.user_id WHERE a.user_id=ANY($1::uuid[]) GROUP BY a.user_id,a.balance",[[a,b]]);assert.ok(reconciliation.rows.every(r=>r.balance===r.ledger_balance));
  const ledgerId=(await pool.query("SELECT id FROM public.trip_credit_ledger WHERE user_id=$1 LIMIT 1",[a])).rows[0].id;await assert.rejects(()=>pool.query("UPDATE public.trip_credit_ledger SET amount=2 WHERE id=$1",[ledgerId]));await assert.rejects(()=>pool.query("DELETE FROM public.trip_credit_ledger WHERE id=$1",[ledgerId]));
  console.log("Trip Credit welcome, idempotency, debit, zero-balance, race, refresh-free, reconciliation, and ledger immutability checks passed.");
}finally{if(users.length){await pool.query("DELETE FROM public.trips WHERE user_id=ANY($1::uuid[])",[users]);await pool.query("DELETE FROM public.users WHERE id=ANY($1::uuid[])",[users]);}await pool.end();}
