import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {getPostgresPool} from "../src/lib/db/postgres.ts";
import {resolveWaypostUserId} from "../src/lib/users/identity.ts";
import {completeTrip,confirmTripTravelOutcome,startTrip,undoTripTravelConfirmation} from "../src/lib/trips/lifecycle.ts";
import {clearOwnedTripPoiVisit,getOwnedTripPoiVisits,PoiVisitError,setOwnedTripPoiVisit} from "../src/lib/trips/poi-visits.ts";
import {finalizeOwnedTrip} from "../src/lib/trips/finalization.ts";
import {refreshFinalRoute} from "../src/lib/trips/final-route-refresh.ts";
import {commitOwnedTripFinalization,createTripWithDraft,getOwnedTrip} from "../src/lib/trips/repository.ts";
import type {FinalRoutePreview} from "../src/types/final-route.ts";
import type {DraftAttractionStop,TripDraft} from "../src/types/trip.ts";

const pool=getPostgresPool();const users:string[]=[];const trips:string[]=[];
const here:FinalRoutePreview={provider:"here",route:{type:"LineString",coordinates:[[-80,35],[-79,36]]},summary:{distanceKm:149,durationSeconds:7000,baseDurationSeconds:6900},diagnostics:{waypointCount:6,sectionCount:1,requestDurationMilliseconds:1}};
let attractionIds:number[]=[];let geonameId=0;
function attraction(id:number,source:"waypost"|"user_attraction",label:string,progress:number):DraftAttractionStop{return{source,attractionId:id,label,coordinates:{lat:35+progress,lon:-80+progress},category:"park",interestCategory:"nature_scenic",rating:4.5,reviewCount:100,duration:"1 hour",visitDuration:{minimumMinutes:60,maximumMinutes:60},routeProgress:progress,personalizedScore:80,individualDetourDistanceKm:2,individualDetourDurationSeconds:300};}
function draft():TripDraft{return{origin:{label:"Origin",coordinates:{lat:35,lon:-80}},stop:null,destination:{label:"Destination",coordinates:{lat:36,lon:-79}},route:{type:"Feature",properties:{},geometry:{type:"LineString",coordinates:[[-80,35],[-79,36]]}},summary:{distanceKm:150,durationSeconds:7200,hasToll:false,hasHighway:true,hasFerry:false},baselineSummary:{distanceKm:150,durationSeconds:7200,hasToll:false,hasHighway:true,hasFerry:false},stops:[{source:"user",label:"Routing waypoint",coordinates:{lat:35.1,lon:-79.9}},attraction(attractionIds[0],"waypost","Waypost park",.25),{type:"overnight",source:"waypost",nightIndex:1,geonameId,label:"Overnight",admin1Code:"NC",countryCode:"US",featureCode:"PPL",population:1000,coordinates:{lat:35.5,lon:-79.5},targetDrivingSeconds:3600,arrivalDrivingSeconds:3600,targetTimeDeviationMinutes:0,detourDurationSeconds:0,detourDistanceKm:0,score:80},attraction(attractionIds[1],"user_attraction","User museum",.75)],alternatives:[],lastEdit:null,preferences:{preferredCategories:[],excludedCategories:[],detourTolerance:"balanced",stopStyle:"balanced",drivingPace:"balanced",selectedTripDays:2,tripDaysOverridden:true},multiDay:{isMultiDay:true,drivingPace:"balanced",recommendedDays:2,selectedDays:2,nights:1,baselineDrivingHours:2,dayOptions:[1,2]},overnightAlternatives:[],dayPlans:[],composition:{targetPoiCount:2,selectedPoiCount:2,detourBudgetSeconds:1000,actualDetourSeconds:0,actualDetourWasClamped:false,valhallaCallCount:1,corridorCandidateCount:2,candidateCountConsidered:2,candidatesAfterDeduplication:2,opportunityShortlistSize:2,candidatePoolTruncated:false,suggestedVisitDuration:{minimumMinutes:60,maximumMinutes:60,hasUnknown:false}}};}
async function user(){const id=await resolveWaypostUserId(`local:poi-visit-test:${randomUUID()}`);users.push(id);return id;}
async function create(userId:string){const value=await createTripWithDraft(userId,draft());if(!value?.currentVersion)throw new Error("fixture failed");trips.push(value.id);return value;}
async function traveled(userId:string){const value=await create(userId);await commitOwnedTripFinalization(userId,value.id,value.currentVersion!.id,value.currentVersion!.updatedAt,here);await startTrip(userId,value.id);await completeTrip(userId,value.id);await confirmTripTravelOutcome(userId,value.id,"traveled");return(await getOwnedTrip(userId,value.id))!;}
async function invariant(tripId:string){return(await pool.query(`SELECT t.status,t.started_at,t.ended_at,t.travel_confirmation_at,t.current_version_id,v.state,v.version_no,v.finalized_at,encode(ST_AsEWKB(v.route_geom),'hex') route_hash,(SELECT count(*)::int FROM trip_stops WHERE trip_version_id=v.id) stop_count,(SELECT encode(ST_AsEWKB(route_geom),'hex') FROM provider_route_cache WHERE trip_version_id=v.id) cache_hash,(SELECT balance FROM trip_credit_accounts WHERE user_id=t.user_id) balance,(SELECT count(*)::int FROM trip_credit_ledger WHERE user_id=t.user_id) ledger_count FROM trips t JOIN trip_versions v ON v.id=t.current_version_id WHERE t.id=$1`,[tripId])).rows[0];}

try{
  attractionIds=(await pool.query("SELECT id FROM attractions ORDER BY id LIMIT 2")).rows.map(row=>Number(row.id));geonameId=Number((await pool.query("SELECT geoname_id FROM settlements ORDER BY geoname_id LIMIT 1")).rows[0].geoname_id);assert.equal(attractionIds.length,2);assert.ok(geonameId);
  const owner=await user();const foreign=await user();const trip=await traveled(owner);const before=await invariant(trip.id);const initial=await getOwnedTripPoiVisits(owner,trip.id);assert.equal(initial.items.length,2);assert.deepEqual(initial.items.map(item=>item.source),["waypost","user"]);assert.ok(initial.items.every(item=>item.outcome===null));
  const stopTypes=(await pool.query("SELECT stop_type FROM trip_stops WHERE trip_version_id=$1 ORDER BY position",[trip.currentVersionId])).rows.map(row=>row.stop_type);assert.deepEqual(stopTypes,["origin","waypoint","attraction","overnight","attraction","destination"]);
  const[first,second]=initial.items;const visited=await setOwnedTripPoiVisit(owner,trip.id,first.tripStopId,"visited");const visitedRetry=await setOwnedTripPoiVisit(owner,trip.id,first.tripStopId,"visited");assert.equal(visitedRetry.confirmedAt,visited.confirmedAt);
  const notVisited=await setOwnedTripPoiVisit(owner,trip.id,second.tripStopId,"not_visited");assert.equal(notVisited.outcome,"not_visited");assert.equal((await getOwnedTripPoiVisits(owner,trip.id)).items.filter(item=>item.outcome).length,2);
  const changed=await setOwnedTripPoiVisit(owner,trip.id,first.tripStopId,"not_visited");assert.notEqual(changed.confirmedAt,visited.confirmedAt);assert.equal((await setOwnedTripPoiVisit(owner,trip.id,first.tripStopId,"visited")).outcome,"visited");assert.equal((await setOwnedTripPoiVisit(owner,trip.id,second.tripStopId,"visited")).outcome,"visited");
  assert.equal((await pool.query("SELECT count(*)::int count FROM trip_poi_visit_confirmations WHERE trip_version_id=$1",[trip.currentVersionId])).rows[0].count,2);
  await clearOwnedTripPoiVisit(owner,trip.id,second.tripStopId);assert.equal((await getOwnedTripPoiVisits(owner,trip.id)).items.find(item=>item.tripStopId===second.tripStopId)?.outcome,null);
  await assert.rejects(()=>getOwnedTripPoiVisits(foreign,trip.id),(e:unknown)=>e instanceof PoiVisitError&&e.code==="TRIP_NOT_FOUND");
  const originId=(await pool.query("SELECT id FROM trip_stops WHERE trip_version_id=$1 AND stop_type='origin'",[trip.currentVersionId])).rows[0].id;await assert.rejects(()=>setOwnedTripPoiVisit(owner,trip.id,originId,"visited"),(e:unknown)=>e instanceof PoiVisitError&&e.code==="TRIP_STOP_NOT_CONFIRMABLE");
  const otherOwner=await user();const other=await traveled(otherOwner);const otherStop=(await getOwnedTripPoiVisits(otherOwner,other.id)).items[0];await assert.rejects(()=>setOwnedTripPoiVisit(owner,trip.id,otherStop.tripStopId,"visited"),(e:unknown)=>e instanceof PoiVisitError&&e.code==="TRIP_STOP_NOT_CONFIRMABLE");await setOwnedTripPoiVisit(otherOwner,other.id,otherStop.tripStopId,"visited");assert.equal((await pool.query("SELECT count(*)::int count FROM trip_poi_visit_confirmations WHERE attraction_id=$1 AND trip_version_id=ANY($2::uuid[])",[attractionIds[0],[trip.currentVersionId,other.currentVersionId]])).rows[0].count,2);
  const race=await Promise.all([setOwnedTripPoiVisit(owner,trip.id,first.tripStopId,"visited"),setOwnedTripPoiVisit(owner,trip.id,first.tripStopId,"not_visited")]);assert.equal(race.length,2);assert.equal((await pool.query("SELECT count(*)::int count FROM trip_poi_visit_confirmations WHERE trip_version_id=$1 AND trip_stop_id=$2",[trip.currentVersionId,first.tripStopId])).rows[0].count,1);
  assert.deepEqual(await invariant(trip.id),before);let finalizeCalls=0;await finalizeOwnedTrip(owner,trip.id,{calculateRoute:async()=>{finalizeCalls++;return here;}});assert.equal(finalizeCalls,0);assert.equal((await getOwnedTripPoiVisits(owner,trip.id)).items.filter(item=>item.outcome).length,1);
  await pool.query("UPDATE provider_route_cache SET fetched_at=now()-interval '31 days',expires_at=now()-interval '1 second' WHERE trip_version_id=$1",[trip.currentVersionId]);await refreshFinalRoute(owner,trip.id,{calculateRoute:async()=>here});assert.equal((await getOwnedTripPoiVisits(owner,trip.id)).items.filter(item=>item.outcome).length,1);
  const lifecycleBefore=await getOwnedTrip(owner,trip.id);await undoTripTravelConfirmation(owner,trip.id);const undone=await getOwnedTrip(owner,trip.id);assert.equal(undone?.status,"completed_unconfirmed");assert.equal(undone?.startedAt,lifecycleBefore?.startedAt);assert.equal(undone?.endedAt,lifecycleBefore?.endedAt);assert.equal((await pool.query("SELECT count(*)::int count FROM trip_poi_visit_confirmations WHERE trip_version_id=$1",[trip.currentVersionId])).rows[0].count,0);await confirmTripTravelOutcome(owner,trip.id,"traveled");assert.ok((await getOwnedTripPoiVisits(owner,trip.id)).items.every(item=>item.outcome===null));
  const invalidOwner=await user();const invalid=await create(invalidOwner);const invalidStopId=(await pool.query("SELECT id FROM trip_stops WHERE trip_version_id=$1 AND stop_type='attraction' LIMIT 1",[invalid.currentVersionId])).rows[0].id;await assert.rejects(()=>setOwnedTripPoiVisit(invalidOwner,invalid.id,invalidStopId,"visited"),(e:unknown)=>e instanceof PoiVisitError&&e.code==="TRIP_NOT_TRAVELED");await commitOwnedTripFinalization(invalidOwner,invalid.id,invalid.currentVersion!.id,invalid.currentVersion!.updatedAt,here);await assert.rejects(()=>getOwnedTripPoiVisits(invalidOwner,invalid.id),(e:unknown)=>e instanceof PoiVisitError&&e.code==="TRIP_NOT_TRAVELED");await startTrip(invalidOwner,invalid.id);await assert.rejects(()=>getOwnedTripPoiVisits(invalidOwner,invalid.id),(e:unknown)=>e instanceof PoiVisitError&&e.code==="TRIP_NOT_TRAVELED");await completeTrip(invalidOwner,invalid.id);await assert.rejects(()=>getOwnedTripPoiVisits(invalidOwner,invalid.id),(e:unknown)=>e instanceof PoiVisitError&&e.code==="TRIP_NOT_TRAVELED");await confirmTripTravelOutcome(invalidOwner,invalid.id,"not_traveled");await assert.rejects(()=>getOwnedTripPoiVisits(invalidOwner,invalid.id),(e:unknown)=>e instanceof PoiVisitError&&e.code==="TRIP_NOT_TRAVELED");assert.equal((await pool.query("SELECT count(*)::int count FROM trip_poi_visit_confirmations WHERE trip_version_id=$1",[invalid.currentVersionId])).rows[0].count,0);
  console.log("POI visit eligibility, tri-state updates, idempotency, corrections, ownership, stop identity, persistence, Undo cascade, and route/cache/credit invariants passed.");
}finally{for(const id of trips)await pool.query("DELETE FROM trips WHERE id=$1",[id]);if(users.length)await pool.query("DELETE FROM users WHERE id=ANY($1::uuid[])",[users]);await pool.end();}
