import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { getPostgresPool } from "../src/lib/db/postgres.ts";
import { resolveWaypostUserId } from "../src/lib/users/identity.ts";
import { commitOwnedTripFinalization, createTripWithDraft, getFinalizedTripWorkspace, refreshOwnedFinalRouteCache } from "../src/lib/trips/repository.ts";
import type { FinalRoutePreview } from "../src/types/final-route.ts";
import type { TripDraft } from "../src/types/trip.ts";

const pool = getPostgresPool(); let userId: string | null = null; let tripId: string | null = null;
const draft: TripDraft = { origin:{label:"A",coordinates:{lat:35,lon:-80}},stop:null,destination:{label:"B",coordinates:{lat:36,lon:-79}},route:{type:"Feature",properties:{},geometry:{type:"LineString",coordinates:[[-80,35],[-79,36]]}},summary:{distanceKm:150,durationSeconds:7200,hasToll:false,hasHighway:true,hasFerry:false},baselineSummary:{distanceKm:150,durationSeconds:7200,hasToll:false,hasHighway:true,hasFerry:false},stops:[],alternatives:[],lastEdit:null,preferences:{preferredCategories:[],excludedCategories:[],detourTolerance:"balanced",stopStyle:"balanced",drivingPace:"balanced",selectedTripDays:1,tripDaysOverridden:true},multiDay:{isMultiDay:false,drivingPace:"balanced",recommendedDays:1,selectedDays:1,nights:0,baselineDrivingHours:2,dayOptions:[1,2]},overnightAlternatives:[],dayPlans:[],composition:{targetPoiCount:1,selectedPoiCount:0,detourBudgetSeconds:1000,actualDetourSeconds:0,actualDetourWasClamped:false,valhallaCallCount:1,corridorCandidateCount:0,candidateCountConsidered:0,candidatesAfterDeduplication:0,opportunityShortlistSize:0,candidatePoolTruncated:false,suggestedVisitDuration:{minimumMinutes:0,maximumMinutes:0,hasUnknown:false}} };
const here: FinalRoutePreview = {provider:"here",route:{type:"LineString",coordinates:[[-80,35],[-79,36]]},summary:{distanceKm:149,durationSeconds:7000,baseDurationSeconds:6900},diagnostics:{waypointCount:2,sectionCount:1,requestDurationMilliseconds:1}};
try {
  userId=await resolveWaypostUserId(`local:cache-test:${randomUUID()}`); const trip=await createTripWithDraft(userId,draft); if(!trip?.currentVersion) throw new Error("fixture failed"); tripId=trip.id;
  const finalized=await commitOwnedTripFinalization(userId,tripId,trip.currentVersion.id,trip.currentVersion.updatedAt,here);
  const snapshot=(await pool.query("SELECT version_no,finalized_at,current_version_id,(SELECT count(*)::int FROM public.trip_stops WHERE trip_version_id=$1) stop_count,encode(ST_AsEWKB(route_geom),'hex') route_hash FROM public.trip_versions JOIN public.trips ON current_version_id=trip_versions.id WHERE trip_versions.id=$1",[trip.currentVersion.id])).rows[0];
  assert.equal((await getFinalizedTripWorkspace(userId,tripId))?.cache.status,"valid");
  const validRetry=await refreshOwnedFinalRouteCache(userId,tripId,trip.currentVersion.id,{...here,summary:{...here.summary,distanceKm:999}}); assert.equal(validRetry.cache.fetchedAt,finalized.cache.fetchedAt); assert.equal(validRetry.finalRoute.summary.distanceKm,here.summary.distanceKm);
  await pool.query("UPDATE public.provider_route_cache SET fetched_at=now()-interval '31 days',expires_at=now()-interval '1 minute' WHERE trip_version_id=$1",[trip.currentVersion.id]);
  const expired=await getFinalizedTripWorkspace(userId,tripId); assert.equal(expired?.cache.status,"expired"); assert.equal(expired?.cache.status==="expired"&&Object.hasOwn(expired.cache,"finalRoute"),false);
  const expiredTimestamp=expired?.cache.status==="expired"?expired.cache.fetchedAt:null; assert.equal((await getFinalizedTripWorkspace(userId,tripId))?.cache.status,"expired"); assert.equal((await pool.query("SELECT fetched_at FROM public.provider_route_cache WHERE trip_version_id=$1",[trip.currentVersion.id])).rows[0].fetched_at.toISOString(),expiredTimestamp);
  const refreshed=await refreshOwnedFinalRouteCache(userId,tripId,trip.currentVersion.id,{...here,summary:{...here.summary,distanceKm:151}}); assert.equal(refreshed.finalRoute.summary.distanceKm,151); assert.equal(new Date(refreshed.cache.expiresAt).getTime()-new Date(refreshed.cache.fetchedAt).getTime(),30*86400000);
  await pool.query("DELETE FROM public.provider_route_cache WHERE trip_version_id=$1",[trip.currentVersion.id]); assert.equal((await getFinalizedTripWorkspace(userId,tripId))?.cache.status,"missing"); await refreshOwnedFinalRouteCache(userId,tripId,trip.currentVersion.id,here); assert.equal((await getFinalizedTripWorkspace(userId,tripId))?.cache.status,"valid");
  const after=(await pool.query("SELECT version_no,finalized_at,current_version_id,(SELECT count(*)::int FROM public.trip_stops WHERE trip_version_id=$1) stop_count,encode(ST_AsEWKB(route_geom),'hex') route_hash FROM public.trip_versions JOIN public.trips ON current_version_id=trip_versions.id WHERE trip_versions.id=$1",[trip.currentVersion.id])).rows[0]; assert.deepEqual(after,snapshot);
  console.log("Final route cache valid/expired/missing, idempotency, TTL, refresh-only mutation, and snapshot invariants passed.");
} finally { if(tripId) await pool.query("DELETE FROM public.trips WHERE id=$1",[tripId]); if(userId) await pool.query("DELETE FROM public.users WHERE id=$1",[userId]); await pool.end(); }
