import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { applyReverseGeocodeLabel, reverseGeocodeResponseIsCurrent } from "../src/lib/trip/map-point-label.ts";
import { parseAttractionEnrichment } from "../src/lib/attraction-enrichment/validation.ts";
import { attractionEnrichmentPath } from "../src/lib/attraction-enrichment/client.ts";
import { distanceMeters, selectExactPlaceCandidate, type VerifiedGooglePlace } from "../src/lib/attraction-enrichment/google-places.ts";
import { ATTRACTION_ENRICHMENT_PROMPT_VERSION, getAttractionEnrichment } from "../src/lib/attraction-enrichment/service.ts";

const coordinates = { lat: 35.2271, lon: -80.8409 };
const point = { input: "35.22710, -80.84090", coordinates, resolvedLabel: "35.22710, -80.84090", source: "map" as const };
const enriched = applyReverseGeocodeLabel(point, coordinates, "Charlotte, NC, USA");
assert.equal(enriched.input, "Charlotte, NC, USA"); assert.deepEqual(enriched.coordinates, coordinates);
assert.equal(applyReverseGeocodeLabel(point, { lat: 36, lon: -80 }, "Stale").input, point.input);
assert.equal(reverseGeocodeResponseIsCurrent(2, 1), false); assert.equal(reverseGeocodeResponseIsCurrent(2, 2), true);

const sources = ["https://example.org/official"];
const valid = parseAttractionEnrichment({ shortDescription: "A grounded place.", whyVisit: "A useful road-trip stop.", highlights: ["One", "Two"], practicalNote: null }, sources);
assert.ok(valid); assert.deepEqual(valid.sourceUrls, sources);
assert.equal(parseAttractionEnrichment({ shortDescription: "Unverified", whyVisit: "Visit.", highlights: ["One", "Two"] }, []), null, "No grounding means no generated content.");
assert.equal(parseAttractionEnrichment({ shortDescription: "Bad", whyVisit: "Bad", highlights: ["One"] }, sources), null);

assert.equal(attractionEnrichmentPath(597021), "/api/attractions/597021/enrichment");
assert.equal(attractionEnrichmentPath(270608), "/api/attractions/270608/enrichment");
assert.notEqual(attractionEnrichmentPath(597021), attractionEnrichmentPath(270608));

process.env.GEMINI_MODEL = "test-model";
const attraction = { id: 7, name: "Real attraction", category: "Museums", rating: 4.7, reviewCount: 200, latitude: 1, longitude: 2 };
const place: VerifiedGooglePlace = { googlePlaceId: "place-real", displayName: "Real attraction", formattedAddress: "1 Real St", latitude: 1.0001, longitude: 2.0001, types: ["museum"], websiteUri: "https://official.example", googleMapsPlaceUri: "https://maps.google.com/real", sourceUrls: ["https://official.example", "https://maps.google.com/real"], distanceMeters: 16 };
assert.ok(distanceMeters(attraction, place) < 20);
assert.equal(selectExactPlaceCandidate(attraction, [{ id: place.googlePlaceId, displayName: { text: place.displayName }, location: { latitude: place.latitude, longitude: place.longitude } }]).candidate?.candidate.id, place.googlePlaceId);
assert.equal(selectExactPlaceCandidate(attraction, [{ id: "wrong", displayName: { text: "Real attraction" }, location: { latitude: 10, longitude: 20 } }]).candidate, null, "A geographically wrong same-name place must be rejected.");
assert.equal(selectExactPlaceCandidate(attraction, [{ id: "a", displayName: { text: "Real attraction" }, location: { latitude: 1.0001, longitude: 2 } }, { id: "b", displayName: { text: "Real attraction" }, location: { latitude: 1.0002, longitude: 2 } }]).reason, "PLACES_AMBIGUOUS");
let resolved = 0; let generated = 0; let saved = 0;
const acceptedResolution = async () => { resolved += 1; return { place, diagnostics: { candidateCount: 1, reason: "PLACES_ACCEPTED" as const } }; };
const cached = await getAttractionEnrichment(7, { findAttraction: async () => attraction, findCached: async () => valid, resolvePlace: acceptedResolution, generate: async () => { generated += 1; return { enrichment: valid, diagnostics: { reason: "GEMINI_ACCEPTED" as const, structuredValidation: true } }; }, save: async () => { saved += 1; } });
assert.deepEqual(cached, valid); assert.equal(resolved, 0); assert.equal(generated, 0); assert.equal(saved, 0);
const expectedGrounded = { ...valid, sourceUrls: place.sourceUrls };
const missed = await getAttractionEnrichment(8, { findAttraction: async () => attraction, findCached: async () => null, resolvePlace: acceptedResolution, generate: async (_attraction, verified) => { generated += 1; assert.equal(verified.googlePlaceId, place.googlePlaceId); return { enrichment: { shortDescription: valid.shortDescription, whyVisit: valid.whyVisit, highlights: valid.highlights, practicalNote: valid.practicalNote }, diagnostics: { reason: "GEMINI_ACCEPTED" as const, structuredValidation: true } }; }, save: async (_id, provider, _model, promptVersion, value, _expiresAt, metadata) => { assert.equal(provider, "google_places"); assert.equal(promptVersion, ATTRACTION_ENRICHMENT_PROMPT_VERSION); assert.deepEqual(value, expectedGrounded); assert.equal(metadata?.googlePlaceId, place.googlePlaceId); saved += 1; } });
assert.deepEqual(missed, expectedGrounded); assert.equal(generated, 1); assert.equal(saved, 1);
const unresolved = await getAttractionEnrichment(9, { findAttraction: async () => attraction, findCached: async () => null, resolvePlace: async () => ({ place: null, diagnostics: { candidateCount: 2, reason: "PLACES_AMBIGUOUS" as const } }), generate: async () => { throw new Error("Gemini must not run for unverified places"); }, save: async () => { throw new Error("must not persist unresolved content"); } });
assert.equal(unresolved, null);
const detailsFailed = await getAttractionEnrichment(11, { findAttraction: async () => attraction, findCached: async () => null, resolvePlace: async () => ({ place: null, diagnostics: { candidateCount: 1, reason: "PLACES_DETAILS_FAILED" as const } }), generate: async () => { throw new Error("Gemini must not run after Details failure"); }, save: async () => { throw new Error("must not cache Details failure"); } });
assert.equal(detailsFailed, null);
const invalid = await getAttractionEnrichment(10, { findAttraction: async () => attraction, findCached: async () => null, resolvePlace: acceptedResolution, generate: async () => ({ enrichment: null, diagnostics: { reason: "GEMINI_SCHEMA_INVALID" as const, structuredValidation: false } }), save: async () => { throw new Error("must not persist invalid content"); } });
assert.equal(invalid, null);

const routeStops = readFileSync(new URL("../src/components/trip/RouteStops.tsx", import.meta.url), "utf8");
const gemini = readFileSync(new URL("../src/lib/attraction-enrichment/gemini.ts", import.meta.url), "utf8");
const places = readFileSync(new URL("../src/lib/attraction-enrichment/google-places.ts", import.meta.url), "utf8");
const card = readFileSync(new URL("../src/components/trip/AttractionEnrichmentCard.tsx", import.meta.url), "utf8");
const cardStyles = readFileSync(new URL("../src/components/trip/TripIntentPanel.module.css", import.meta.url), "utf8");
const mapCanvas = readFileSync(new URL("../src/components/map/MapCanvas.tsx", import.meta.url), "utf8");
const planner = readFileSync(new URL("../src/components/trip/TripPlanner.tsx", import.meta.url), "utf8");
const persistence = readFileSync(new URL("../src/lib/trips/repository.ts", import.meta.url), "utf8");
assert.match(routeStops, /selected \? <AttractionEnrichmentCard/); assert.match(routeStops, /selected=\{props\.activePoiId === stop\.attractionId\}/); assert.match(routeStops, /stop\.category/);
assert.doesNotMatch(routeStops, /emphasized \? <AttractionEnrichmentCard/, "Hover emphasis must never mount an enrichment request.");
assert.match(routeStops, /selectableRouteStop/); assert.match(routeStops, /onClick=\{\(\) => props\.onPoiSelect\(stop\.attractionId\)\}/);
assert.doesNotMatch(routeStops, /overnight[\s\S]*AttractionEnrichmentCard/);
assert.match(gemini, /process\.env\.GEMINI_API_KEY/); assert.match(gemini, /process\.env\.GEMINI_MODEL/); assert.doesNotMatch(gemini, /googleSearch|groundingMetadata/);
assert.match(gemini, /ONLY the supplied verified factual JSON/); assert.match(places, /places:searchText/); assert.match(places, /googleMapsLinks/);
assert.equal(ATTRACTION_ENRICHMENT_PROMPT_VERSION, "p1.26-v3");
assert.doesNotMatch(gemini, /distanceKm|durationSeconds|route geometry/);
assert.match(planner, /\/api\/geocode\/reverse/); assert.match(planner, /reverseGeocodeSequence/);
assert.match(persistence, /attractionId/, "Persistence/reconstruction must retain canonical attraction identity.");
assert.match(card, /Official website/); assert.match(card, /Google Maps/); assert.doesNotMatch(card, /<details>|>Source</);
assert.match(cardStyles, /\.enrichmentHighlights \{[^}]*display: flex !important;[^}]*flex-flow: row wrap;/);
assert.match(cardStyles, /\.routeEditor \.enrichmentHighlights li \{[^}]*display: inline-flex;[^}]*flex: 0 1 auto;[^}]*width: auto;[^}]*min-width: 0;[^}]*max-width: 100%;/);
assert.match(cardStyles, /\.routeEditor \.enrichmentHighlights li \{[^}]*white-space: normal;[^}]*word-break: normal;[^}]*overflow-wrap: break-word;/);
assert.match(cardStyles, /\.selectableRouteStop \{[^}]*cursor: pointer;/); assert.match(mapCanvas, /marker\.getElement\(\)\.style\.cursor = "pointer"/);
console.log("Reverse-geocode authority/fallback/stale guards and grounded attraction enrichment cache/fallback invariants passed.");
