"use client";

import { useEffect, useState } from "react";
import type { PoiVisitItem, PoiVisitOutcome, PoiVisitsResponse } from "@/types/poi-visits";
import styles from "./PoiVisitPanel.module.css";

export default function PoiVisitPanel({tripId}:{tripId:string}){
  const[items,setItems]=useState<PoiVisitItem[]|null>(null);const[error,setError]=useState<string|null>(null);const[savingId,setSavingId]=useState<string|null>(null);const[editingId,setEditingId]=useState<string|null>(null);
  useEffect(()=>{let cancelled=false;void fetch(`/api/trips/${tripId}/poi-visits`).then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<PoiVisitsResponse>;}).then(data=>{if(!cancelled){setItems(data.items);setError(null);}}).catch(()=>{if(!cancelled)setError("Places could not be loaded.");});return()=>{cancelled=true;};},[tripId]);
  async function setOutcome(item:PoiVisitItem,outcome:PoiVisitOutcome){setSavingId(item.tripStopId);setError(null);try{const response=await fetch(`/api/trips/${tripId}/poi-visits/${item.tripStopId}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({outcome})});if(!response.ok)throw new Error();const updated=await response.json() as PoiVisitItem;setItems(current=>current?.map(value=>value.tripStopId===updated.tripStopId?updated:value)??current);setEditingId(null);}catch{setError("That visit confirmation could not be saved.");}finally{setSavingId(null);}}
  async function clear(item:PoiVisitItem){setSavingId(item.tripStopId);setError(null);try{const response=await fetch(`/api/trips/${tripId}/poi-visits/${item.tripStopId}`,{method:"DELETE"});if(!response.ok)throw new Error();setItems(current=>current?.map(value=>value.tripStopId===item.tripStopId?{...value,outcome:null,confirmedAt:null}:value)??current);setEditingId(null);}catch{setError("That visit confirmation could not be cleared.");}finally{setSavingId(null);}}
  const visited=items?.filter(item=>item.outcome==="visited").length??0;const notVisited=items?.filter(item=>item.outcome==="not_visited").length??0;const unconfirmed=(items?.length??0)-visited-notVisited;
  return <section className={styles.panel} aria-labelledby="poi-visits-heading"><h3 id="poi-visits-heading">Places on this trip</h3><p>Tell Waypost which planned stops you actually visited.</p>{items?<small>{items.length} planned place{items.length===1?"":"s"} · {visited} visited · {notVisited} not visited · {unconfirmed} not confirmed</small>:null}{error?<p role="alert">{error}</p>:null}{items===null&&!error?<p>Loading places…</p>:null}{items?.length===0?<p>No attraction stops were planned for this trip.</p>:null}<ul>{items?.map(item=><li key={item.tripStopId}><div><strong>{item.name}</strong><small>{item.source==="waypost"?"Waypost suggestion":"Added by you"}</small></div>{item.outcome&&editingId!==item.tripStopId?<div><span>{item.outcome==="visited"?"Visited ✓":"Didn't visit"}</span><button type="button" onClick={()=>setEditingId(item.tripStopId)}>Change</button></div>:<div><button type="button" disabled={savingId===item.tripStopId} onClick={()=>void setOutcome(item,"visited")}>Visited</button><button type="button" disabled={savingId===item.tripStopId} onClick={()=>void setOutcome(item,"not_visited")}>Didn&apos;t visit</button>{item.outcome?<button type="button" disabled={savingId===item.tripStopId} onClick={()=>void clear(item)}>Clear</button>:null}</div>}</li>)}</ul></section>;
}
